-- 오랜 기간 보호한 동물(2)

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
JOIN ANIMAL_INS AI
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE (AO.DATETIME - AI.DATETIME) > 0
ORDER BY (AO.DATETIME - AI.DATETIME) DESC
LIMIT 2
;